<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="test01" duration-ms="78" started-at="2020-02-20T07:17:48Z" finished-at="2020-02-20T07:17:48Z">
    <groups>
      <group name="other">
        <method signature="HelloTestNG.success_test_02()[pri:0, instance:testCase.HelloTestNG@31b7dea0]" name="success_test_02" class="testCase.HelloTestNG"/>
      </group> <!-- other -->
      <group name="main">
        <method signature="HelloTestNG.success_test_01()[pri:0, instance:testCase.HelloTestNG@31b7dea0]" name="success_test_01" class="testCase.HelloTestNG"/>
      </group> <!-- main -->
    </groups>
    <test name="autotest-mainTest" duration-ms="78" started-at="2020-02-20T07:17:48Z" finished-at="2020-02-20T07:17:48Z">
      <class name="testCase.HelloTestNG">
        <test-method status="PASS" signature="success_test_01()[pri:0, instance:testCase.HelloTestNG@31b7dea0]" name="success_test_01" duration-ms="23" started-at="2020-02-20T15:17:48Z" finished-at="2020-02-20T15:17:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- success_test_01 -->
        <test-method status="FAIL" signature="success_test_02()[pri:0, instance:testCase.HelloTestNG@31b7dea0]" name="success_test_02" duration-ms="1" started-at="2020-02-20T15:17:48Z" finished-at="2020-02-20T15:17:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at testCase.HelloTestNG.success_test_02(HelloTestNG.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- success_test_02 -->
      </class> <!-- testCase.HelloTestNG -->
    </test> <!-- autotest-mainTest -->
  </suite> <!-- test01 -->
</testng-results>
